config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index' 
  
  devise_for :users    
  resources :products, :clients, :operations, :users

  #OPERACIONES  
  put "/operations/:id/print" => "operations#print"
  put "/operations/:id/pay" => "operations#pay"
  put "/operations/:id/cancel" => "operations#cancel"
  get 'borradores' => 'operations#borradores'
  get 'impresas' => 'operations#impresas'
  get 'pagadas' => 'operations#pagadas'
  get 'canceladas' => 'operations#canceladas'
  #Compras
  get 'compras' => 'operations#compras'
  get 'compras/borrador' => 'operations#compras_borrador'
  get 'compras/impresas' => 'operations#compras_impresas'
  get 'compras/contado' => 'operations#compras_contado'
  get 'compras/credito' => 'operations#compras_credito'
  #Ventas
  get 'ventas' => 'operations#ventas'
  get 'ventas/borrador' => 'operations#ventas_borrador'
  get 'ventas/impresas' => 'operations#ventas_impresas'
  get 'ventas/contado' => 'operations#ventas_contado'
  get 'ventas/credito' => 'operations#ventas_credito'

  #Clientes 
  
  get 'clientes' => 'clients#clientes'
  get 'clientes/recurrentes' => 'clients#clientes_recurrentes'
  get 'clientes/puntuales' => 'clients#clientes_puntuales'
  #Proveedores
  get 'proveedores' => 'clients#proveedores'
  get 'proveedores/recurrentes' => 'clients#proveedores_recurrentes'
  get 'proveedores/puntuales' => 'clients#proveedores_puntuales'
  #Sponsors
  get 'sponsors' => 'clients#sponsors'
  get 'sponsors/recurrentes' => 'clients#sponsors_recurrentes'
  get 'sponsors/puntuales' => 'clients#sponsors_puntuales'


end

app/views/partials/_navigation.html.erb
<header>
	<nav class="navbar navbar-default navbar-fixed-top be-blue", style="background-image:url(fondo.jpg);">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<%= link_to image_tag("logo.png", height: '50', width: '50'), root_path, :class => 'navbar-brand' %>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<% if user_signed_in? && current_user.is_admin? %>
					<ul class="nav navbar-nav">
					<li><%= link_to "Usuarios", users_path, :class => 'text-white font-medium' %></li>
				<%end%>
					</ul>
				<% if user_signed_in? %>
					<ul class="nav navbar-nav">
						<li><%= link_to "Facturas", operations_path, :class => 'text-white font-medium' %></li>
						<li><%= link_to "Asociados", clients_path, :class => 'text-white font-medium' %></li>
						<li><%= link_to "Productos", products_path, :class => 'text-white font-medium' %></li>					
					</ul>
					<ul class="nav navbar-nav navbar-rigth">
					<li>
						<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => 'text-white font-medium', data: { confirm: '¿Estás seguro salir?' } %>
					</li>
					</ul>
				<%else%>
					<ul class="nav navbar-nav">
						<li>
							<%= link_to "Iniciar sesión", new_user_session_path, :class => 'text-white font-medium' %>
						</li>
						<li>
							<%= link_to "Crear cuenta", new_user_registration_path, :class => 'text-white font-medium' %>
						</li>
					</ul>
				<%end%>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
</header>