config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index' 
  
  devise_for :users    
  resources :products, :clients, :operations, :users

  #OPERACIONES  
  put "/operations/:id/print" => "operations#print"
  put "/operations/:id/pay" => "operations#pay"
  put "/operations/:id/cancel" => "operations#cancel"
  get 'borradores' => 'operations#borradores'
  get 'impresas' => 'operations#impresas'
  get 'pagadas' => 'operations#pagadas'
  get 'canceladas' => 'operations#canceladas'
  #Compras
  get 'compras' => 'operations#compras'
  get 'compras/borrador' => 'operations#compras_borrador'
  get 'compras/impresas' => 'operations#compras_impresas'
  get 'compras/contado' => 'operations#compras_contado'
  get 'compras/credito' => 'operations#compras_credito'
  #Ventas
  get 'ventas' => 'operations#ventas'
  get 'ventas/borrador' => 'operations#ventas_borrador'
  get 'ventas/impresas' => 'operations#ventas_impresas'
  get 'ventas/contado' => 'operations#ventas_contado'
  get 'ventas/credito' => 'operations#ventas_credito'

  #Clientes 
  
  get 'clientes' => 'clients#clientes'
  get 'clientes/recurrentes' => 'clients#clientes_recurrentes'
  get 'clientes/puntuales' => 'clients#clientes_puntuales'
  #Proveedores
  get 'proveedores' => 'clients#proveedores'
  get 'proveedores/recurrentes' => 'clients#proveedores_recurrentes'
  get 'proveedores/puntuales' => 'clients#proveedores_puntuales'
  #Sponsors
  get 'sponsors' => 'clients#sponsors'
  get 'sponsors/recurrentes' => 'clients#sponsors_recurrentes'
  get 'sponsors/puntuales' => 'clients#sponsors_puntuales'


end

app/models/client.rb
class Client < ActiveRecord::Base
  include Gravtastic
  gravtastic
  
  belongs_to :user
  has_many :operations
  validates :nombre, :identificacion, :email, :telefono, :direccion, :tipo, :frecuencia, 
  :presence => {:message => "No debe estar en blanco"}
  validates :nombre, :apellido, :identificacion, :telefono, length: { in: 2..15,
    too_long: "%{count} caracteres es el máximo permitido",
    too_short: "%{count} caracteres es el minimo permitido" }
  validates :email, :identificacion, uniqueness: true
  validates :email, length: { maximum: 30,
    too_long: "%{count} caracteres es el máximo permitido" }
  validates :direccion, :descripcion, length: { maximum: 150,
    too_long: "%{count} caracteres es el máximo permitido" }
  validates :tipo, inclusion: { in: :tipo }
  validates :frecuencia, inclusion: { in: :frecuencia }
  enum tipo: [ :Cliente, :Sponsor, :Proveedor ]
	enum frecuencia: [ :Recurrente, :Puntual ]

  scope :ultimos, ->{ order(created_at: :asc) }
  scope :clientes, ->{ where(tipo: 0) }
  scope :sponsor, ->{ where(tipo: 1) }
  scope :proveedores, ->{ where(tipo: 2) }
  scope :recurrentes, ->{ where(frecuencia: 0) }
  scope :puntuales, ->{ where(tipo: 1) }

  def full_name    
    [nombre, apellido].join(' ')    
  end   
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_asistente!, only: [:edit, :update, :new]
  before_action :authenticate_admin!, only: [:destroy]

  def index
		@clients = Client.paginate(page: params[:page],per_page:5).ultimos 
	end

	def show		
	end

	def new
		@client = Client.new
	end

	def edit
	end
  
  def create
    @client = current_user.clients.new(client_params)
    respond_to do |format|
      if @client.save
          format.html { redirect_to @client, :notice => 'El cliente fue creado exitosamente' }
          format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end   
    end
  end


	def update
		respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, :notice => 'El cliente fue editado exitosamente' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, :notice => 'El cliente fue borrado exitosamente' }
      format.json { head :no_content }
    end
	end

  def clientes 
    @clients = Client.paginate(page: params[:page],per_page:5).clientes
    render :index
  end

  def clientes_recurrentes
    @clients = Client.paginate(page: params[:page],per_page:5).clientes.recurrentes
    render :index
  end

  def clientes_puntuales
    @clients = Client.paginate(page: params[:page],per_page:5).clientes.puntuales
    render :index
  end

  def sponsors 
    @clients = Client.paginate(page: params[:page],per_page:5).sponsor
    render :index
  end

  def sponsors_recurrentes
    @clients = Client.paginate(page: params[:page],per_page:5).sponsor.recurrentes
    render :index
  end

  def sponsors_puntuales
    @clients = Client.paginate(page: params[:page],per_page:5).sponsor.puntuales
    render :index
  end

  def proveedores 
    @clients = Client.paginate(page: params[:page],per_page:5).proveedores
    render :index
  end

  def proveedores_recurrentes
    @clients = Client.paginate(page: params[:page],per_page:5).proveedores.recurrentes
    render :index
  end

  def proveedores_puntuales
    @clients = Client.paginate(page: params[:page],per_page:5).proveedores.puntuales
    render :index
  end

	private

	def set_client
		@client = Client.find(params[:id])
	end

	def client_params
		params.require(:client).permit(:nombre, :apellido, 
			:identificacion, :email, :telefono, :direccion, 
			:descripcion, :tipo, :frecuencia, :user_id)
	end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clientes.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <th>Avatar</th>
      <th>Nombre y Apellido</th>
      <th>Identificación</th>
      <th>Email</th>
      <th>Teléfono</th>
    </thead>
    <tbody>
      <% @clients.each do |client| %>
      <tr>    
        <td><div>
          <%= image_tag client.gravatar_url %>
        </div></td>
        <td class="link-index"><%= link_to client.full_name, client %></td>
        <td><%= client.identificacion %></td>
        <td><%= client.email %></td>
        <td><%= client.telefono %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clients/_footer.html.erb
<footer>
  <ul class="nav nav-pills">
    <li class="boton-footer active", role="presentation", style="a:hover:green"><%= link_to "Retornar", "/clients" %> </li>
    <% if current_user.is_asistente? %>
      <li class="boton-footer", role="presentation", style="hover:green"><%= link_to  "Editar", edit_client_path(@client) %></li>      
    <%end%>    
    <% if current_user.is_admin? %>
      <li class="boton-footer", role="presentation", style="hover:green"><%= link_to 'Eliminar', @client, method: :delete, data: { confirm: '¿Estás seguro de eliminar este cliente?' } %></li>
    <%end%>    
  </ul>
</footer>

app/views/clients/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> Cliente</h1>
<% @client.errors %>
	<%= semantic_form_for @client do |f| %>
	<%= f.input :nombre, placeholder: "Nombre" %>
	<%= f.input :apellido, placeholder: "Apellido" %>
	<%= f.input :identificacion,label: "Cédula de Identidad o RIF", placeholder: "Identificacion" %>
	<%= f.input :email,label: "Correo electrónico", placeholder: "Email" %>
	<%= f.input :telefono, placeholder: "Teléfono" %>
	<%= f.input :direccion, placeholder: "Dirección" %>
	<%= f.input :descripcion, placeholder: "Descripción" %>
	<%= f.input :tipo, :as => :select, :collection => Client.tipos.keys.to_a %>
	<%= f.input :frecuencia, :as => :select, :collection => Client.frecuencia.keys.to_a %>
	<ul class="nav nav-pills", style="margin:0;padding:0">
  <li class="boton-footer", role="presentation", style="hover:green"> 
    <%= f.submit "Guardar", :class => 'text-hack font-medium', style:"width:200px;height:50px" %>
  </li>
  <li class="boton-footer", role="presentation", style="hover:green">
  <%if name = "Editar"%>
    <%= link_to "Cancelar", @client, :class => 'text-red font-medium', style:"width:200px;height:50px;background-color:#E4E4E4;border:1px solid grey;border-radius:0;" %>  
  <%else%>
    <%= link_to "Cancelar", "/clients", :class => 'text-red font-medium', style:"width:200px;height:50px;background-color:#E4E4E4;border:1px solid grey;border-radius:0;" %>     
  <%end%>
  </li>
</ul>

	<% end %>	

app/views/clients/_navigation.html.erb
<ul class="nav nav-tabs nav-justified">
  <li role="presentation" style="background-color:#e4e4e4;" ><%= link_to "Nuevo Asociado", new_client_path %></li>
  <li role="presentation" ><%= link_to "Todos", clients_path %></li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Clientes <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Clientes", clientes_path %></li>      
      <li class="divider"></li>
      <li><%= link_to "Recurrentes", clientes_recurrentes_path %></li>
      <li><%= link_to "Puntuales", clientes_puntuales_path %></li>      
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Sponsor <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Sponsors", sponsors_path %></li>      
      <li class="divider"></li>
      <li><%= link_to "Recurrentes", sponsors_recurrentes_path %></li>
      <li><%= link_to "Puntuales", sponsors_puntuales_path %></li>  
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Proveedores <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Proveedores", proveedores_path %></li>      
      <li class="divider"></li>
      <li><%= link_to "Recurrentes", proveedores_recurrentes_path %></li>
      <li><%= link_to "Puntuales", proveedores_puntuales_path %></li>  
    </ul>
  </li>
</ul>

app/views/clients/edit.html.erb
<div class="form-center">
	<%= render "form", name: "Editar" %>
</div>

app/views/clients/index.html.erb
<div class="form-center">  
  <strong class="font-large">Clientes:</strong> 
	<%= render "navigation" %>
  <%= render "clientes" %>
  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @clients %>
      <br><br>
    </div>
    <%= will_paginate @clients, :container => false %>
  </div>  
</div>

app/views/clients/new.html.erb
<div class="form-center">
	<%= render "form" %>
</div>

app/views/clients/show.html.erb
<div class="show-center">
  <h1><%= @client.tipo %>: <strong><%= @client.full_name %></strong></h1> 
  <%= image_tag @client.gravatar_url %> 
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <th>Identificacion</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th>Dirección</th>
        <th>Descripción</th>
        <th>Frecuencia</th>
        <th>Creado por</th>
      </thead>
      <tbody>
        <tr>
          <td><%= @client.identificacion %></td>
          <td><%= @client.email %></td>
          <td><%= @client.telefono %></td>
          <td><%= @client.direccion %></td>
          <td><%= @client.descripcion %></td>
          <td><%= @client.frecuencia %></td>
          <% unless @client.user.nil? %>
          <td><%= @client.user.username %></td>
          <%end%>
        </tr>
      </tbody>
    </table>
  </div>
  <%= render "footer" %> 
</div>