config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index' 
  
  devise_for :users    
  resources :products, :clients, :operations, :users

  #OPERACIONES  
  put "/operations/:id/print" => "operations#print"
  put "/operations/:id/pay" => "operations#pay"
  put "/operations/:id/cancel" => "operations#cancel"
  get 'borradores' => 'operations#borradores'
  get 'impresas' => 'operations#impresas'
  get 'pagadas' => 'operations#pagadas'
  get 'canceladas' => 'operations#canceladas'
  #Compras
  get 'compras' => 'operations#compras'
  get 'compras/borrador' => 'operations#compras_borrador'
  get 'compras/impresas' => 'operations#compras_impresas'
  get 'compras/contado' => 'operations#compras_contado'
  get 'compras/credito' => 'operations#compras_credito'
  #Ventas
  get 'ventas' => 'operations#ventas'
  get 'ventas/borrador' => 'operations#ventas_borrador'
  get 'ventas/impresas' => 'operations#ventas_impresas'
  get 'ventas/contado' => 'operations#ventas_contado'
  get 'ventas/credito' => 'operations#ventas_credito'

  #Clientes 
  
  get 'clientes' => 'clients#clientes'
  get 'clientes/recurrentes' => 'clients#clientes_recurrentes'
  get 'clientes/puntuales' => 'clients#clientes_puntuales'
  #Proveedores
  get 'proveedores' => 'clients#proveedores'
  get 'proveedores/recurrentes' => 'clients#proveedores_recurrentes'
  get 'proveedores/puntuales' => 'clients#proveedores_puntuales'
  #Sponsors
  get 'sponsors' => 'clients#sponsors'
  get 'sponsors/recurrentes' => 'clients#sponsors_recurrentes'
  get 'sponsors/puntuales' => 'clients#sponsors_puntuales'


end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :operations
  # validates :cantidad, numericality: { only_integer: true }, length: { maximum: 2,
  #   too_long: "%{count} caracteres es el máximo permitido" }
	validates :producto, :precio, :presence => {:message => "No debe estar en blanco"}
  validates :producto, length: { maximum: 30,
    too_long: "%{count} caracteres es el máximo permitido" }
  validates :descripcion, length: { maximum: 150,
    too_long: "%{count} caracteres es el máximo permitido" }
  validates :precio, length: { maximum: 10,
    too_long: "%{count} caracteres es el máximo permitido" }

  scope :ultimos, ->{ order(created_at: :asc) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_asistente!, only: [:edit, :update, :new]
  before_action :authenticate_admin!, only: [:destroy]

	def index
		@products = Product.paginate(page: params[:page],per_page:5).ultimos
	end

	def show		
	end

	def new
		@product = Product.new
	end

	def edit
	end
  
  def create
    @product = current_user.products.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'El producto fue creado exitosamente' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


	def update
		respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, :notice => 'El producto fue editado exitosamente' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end		
	end

	def destroy
		@product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, :notice => 'El producto fue borrado exitosamente' }
      format.json { head :no_content }
    end
	end

	private

	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
		params.require(:product).permit(:producto, :descripcion, :precio, :user_id)
	end
end

app/views/products/_footer.html.erb
<footer>
  <ul class="nav nav-pills">
    <li class="boton-footer active", role="presentation", style="a:hover:green"><%= link_to "Retornar", "/products" %> </li>
    <% if current_user.is_asistente? %>
      <li class="boton-footer", role="presentation", style="hover:green"><%= link_to  "Editar", edit_product_path(@product) %></li>      
    <%end%>    
    <% if current_user.is_admin? %>
      <li class="boton-footer", role="presentation", style="hover:green"><%= link_to 'Eliminar', @product, method: :delete, data: { confirm: '¿Estás seguro de eliminar este producto?' } %></li>
    <%end%>    
  </ul>
</footer>

app/views/products/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> Producto</h1>
<% @product.errors %>
<%= semantic_form_for @product do |f| %>
<%= f.input :producto, placeholder: "Nombre del producto aquí" %>
<%= f.input :descripcion, placeholder: "Descripción" %>
<%= f.input :precio, placeholder: "Precio" %>
<ul class="nav nav-pills", style="margin:0;padding:0">

  <li class="boton-footer", role="presentation", style="hover:green"> 
    <%= f.submit "Guardar", :class => 'text-hack font-medium', style:"width:200px;height:50px" %>
  </li>
  <li class="boton-footer", role="presentation", style="hover:green">
  <%if name = "Editar"%>
    <%= link_to "Cancelar", @product, :class => 'text-red font-medium', style:"width:200px;height:50px;background-color:#E4E4E4;border:1px solid grey;border-radius:0;" %>  
  <%else%>
    <%= link_to "Cancelar", "/products", :class => 'text-red font-medium', style:"width:200px;height:50px;background-color:#E4E4E4;border:1px solid grey;border-radius:0;" %>     
  <%end%>
  </li> 
</ul>
<% end %>	

app/views/products/edit.html.erb
<div class="form-center">
	<%= render "form", name: "Editar" %>
</div>

app/views/products/index.html.erb
<div class="form-center">
<strong class="font-large">Productos:</strong>  
	
	<ul class="nav nav-tabs">
  <li role="presentation" style="background-color:#e4e4e4;" ><%= link_to "Crear Nuevo Producto", new_product_path %></li>  
  </ul>

	<div class="table-responsive">
		<table class="table table-hover">
			<thead>
				<th>N°</th>
				<th>Nombre</th>
				<th>Descripción</th>
				<th>Precio</th>
				<th></th>
				<th></th>
				<th></th>
			</thead>
			<tbody>
				<% @products.each_with_index do |product, index| %>
				<tr>
					<td><%= index + 1 %></td>
					<td class="link-index"><%= link_to product.producto, product %></td>
					<td><%= product.descripcion %></td>
					<td><%= product.precio %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @products %>
      <br><br>
    </div>
    <%= will_paginate @products, :container => false %>
  </div>  
</div>

app/views/products/new.html.erb
<div class="form-center">
	<%= render "form" %>
</div>

app/views/products/show.html.erb
<div class="show-center">
  <h1>Producto: <strong><%= @product.producto %></strong></h1>  
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Precio</th>
        <th>Creado por</th>
      </thead>
      <tbody>
        <tr>
          <td><%= @product.producto %></td>
          <td><%= @product.descripcion %></td>
          <td><%= @product.precio %></td>
          <% unless @product.user.nil? %>
          <td><%= @product.user.username %></td>
          <%end%>
        </tr>
      </tbody>
    </table>
  </div>
  <hr>
  <%= render "footer" %> 
</div>
<br>
<br>
<br>