config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index' 
  
  devise_for :users    
  resources :products, :clients, :operations, :users

  #OPERACIONES  
  put "/operations/:id/print" => "operations#print"
  put "/operations/:id/pay" => "operations#pay"
  put "/operations/:id/cancel" => "operations#cancel"
  get 'borradores' => 'operations#borradores'
  get 'impresas' => 'operations#impresas'
  get 'pagadas' => 'operations#pagadas'
  get 'canceladas' => 'operations#canceladas'
  #Compras
  get 'compras' => 'operations#compras'
  get 'compras/borrador' => 'operations#compras_borrador'
  get 'compras/impresas' => 'operations#compras_impresas'
  get 'compras/contado' => 'operations#compras_contado'
  get 'compras/credito' => 'operations#compras_credito'
  #Ventas
  get 'ventas' => 'operations#ventas'
  get 'ventas/borrador' => 'operations#ventas_borrador'
  get 'ventas/impresas' => 'operations#ventas_impresas'
  get 'ventas/contado' => 'operations#ventas_contado'
  get 'ventas/credito' => 'operations#ventas_credito'

  #Clientes 
  
  get 'clientes' => 'clients#clientes'
  get 'clientes/recurrentes' => 'clients#clientes_recurrentes'
  get 'clientes/puntuales' => 'clients#clientes_puntuales'
  #Proveedores
  get 'proveedores' => 'clients#proveedores'
  get 'proveedores/recurrentes' => 'clients#proveedores_recurrentes'
  get 'proveedores/puntuales' => 'clients#proveedores_puntuales'
  #Sponsors
  get 'sponsors' => 'clients#sponsors'
  get 'sponsors/recurrentes' => 'clients#sponsors_recurrentes'
  get 'sponsors/puntuales' => 'clients#sponsors_puntuales'


end

app/models/operation.rb
class Operation < ActiveRecord::Base
  include AASM

  belongs_to :user
  belongs_to :client
  belongs_to :product

  validates :cantidad, :fecha, :client_id, :product_id, :presence => {:message => "No debe estar en blanco"}
  validates :cantidad, numericality: { only_integer: true }
  validates :operacion, inclusion: { in: :operacion }
  validates :pago, inclusion: { in: :pago }
  enum operacion: [ :Compra, :Venta ]
  enum pago: [ :Contado, :Credito ]
  after_create :send_mail
  
  has_attached_file :cover, styles: { medium: "300x300>", thumb: "100x100>"}, :default_url => "missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  scope :ultimos, ->{ order(created_at: :asc) }
  scope :borradores, ->{ where(state: "Borrador") }
  scope :impresas, ->{ where(state: "Emitida") }
  scope :pagadas, ->{ where(state: "Pagada") }
  scope :canceladas, ->{ where(state: "Anulada") }
  scope :compras, ->{ where(operacion: 0) }
  scope :ventas, ->{ where(operacion: 1) }
  scope :contado, ->{ where(pago: 0) }
  scope :credito, ->{ where(pago: 1) }

  aasm column: "state" do
    state :Borrador, initial: true
    state :Emitida
    state :Pagada
    state :Anulada

    event :print do 
      transitions from: :Borrador, to: :Emitida
    end

    event :pay do 
      transitions from: [:Borrador, :Emitida], to: :Pagada
    end

    event :cancel do 
      transitions from: [:Borrador, :Emitida, :Pagada], to: :Anulada
    end
  end 

  def self.invoice operation, product
    tasa = operation[:tasa].to_i
    cantidad = operation[:cantidad].to_i
    subtotal = (cantidad*product.precio.to_i)
    impuestos = (tasa*subtotal/100)
    total = (subtotal+impuestos) 
    operation[:subtotal] = subtotal
    operation[:impuestos] = impuestos
    operation[:total] = total    
    operation.save
  end

  def send_mail
     OperationMailer.new_operation(self).deliver_now
  end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_operation, only: [:show, :edit, :update, :destroy, :print, :cancel, :pay]
  before_action :authenticate_asistente!, only: [:edit, :update, :new, :pay, :print]
  before_action :authenticate_admin!, only: [:destroy, :cancel]
  prawnto :prawn => { :page_size => 'A4', :margin => 20 }

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.paginate(page: params[:page],per_page:5).ultimos    
  end

  # GET /operations/1
  # GET /operations/1.json
  def show    
    operation = Operation.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = FacturaPdf.new(@operation)
        send_data pdf.render, filename: "factura_#{@operation.id}.pdf", type: 'application/pdf'
      end
    end 
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = current_user.operations.new(operation_params)
    @product = Product.find(operation_params[:product_id])
    operation = @operation
    product = @product
    respond_to do |format|
      if Operation.invoice operation, product        
        @operation.save
        format.html { redirect_to @operation, :notice => 'La operación fue creada exitosamente y se envió el email al interesado' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    @product = Product.find(operation_params[:product_id])
    operation = @operation
    product = @product
    respond_to do |format|
      if Operation.invoice operation, product 
        @operation.update(operation_params)
        if operation.subtotal != product.precio*operation.cantidad
          Operation.invoice operation, product 
        else
          @operation.update(operation_params)
        end  
        @operation.update(operation_params)
        format.html { redirect_to @operation, :notice => 'La operación fue editada exitosamente' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, 
        :alert => 'La factura fue borrada exitosamente' }
      format.json { head :no_content }
    end
  end

  #PUT /operations/:id/print
  def print 
    respond_to do |format|
      if @operation.print!
        format.html { redirect_to @operation, :notice => 'La factura fue emitida exitosamente' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  def pay  
    respond_to do |format|
      if @operation.pay!
        format.html { redirect_to @operation, :notice => 'La factura fue pagada exitosamente' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel 
    respond_to do |format|
      if @operation.cancel!
        format.html { redirect_to @operation, :notice => 'La factura fue anulada exitosamente' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  #FACTURAS:
  def borradores 
    @operations = Operation.paginate(page: params[:page],per_page:5).borradores
    render :index
  end 

  def impresas 
    @operations = Operation.paginate(page: params[:page],per_page:5).impresas
    render :index
  end

  def pagadas 
    @operations = Operation.paginate(page: params[:page],per_page:5).pagadas
    render :index
  end 

  def canceladas 
    @operations = Operation.paginate(page: params[:page],per_page:5).canceladas
    render :index
  end


  #VENTAS
  def ventas 
    @operations = Operation.paginate(page: params[:page],per_page:5).ventas
    render :index
  end  

  def ventas_borrador
    @operations = Operation.paginate(page: params[:page],per_page:5).ventas.borradores
    render :index
  end  

  def ventas_impresas
    @operations = Operation.paginate(page: params[:page],per_page:5).ventas.impresas
    render :index
  end

  def ventas_contado 
    @operations = Operation.paginate(page: params[:page],per_page:5).ventas.contado
    render :index
  end

  def ventas_credito 
    @operations = Operation.paginate(page: params[:page],per_page:5).ventas.credito
    render :index
  end

  #COMPRAS
  def compras 
    @operations = Operation.paginate(page: params[:page],per_page:5).compras
    render :index
  end  

  def compras_borrador
    @operations = Operation.paginate(page: params[:page],per_page:5).compras.borradores
    render :index
  end  

  def compras_impresas
    @operations = Operation.paginate(page: params[:page],per_page:5).compras.impresas
    render :index
  end

  def compras_contado 
    @operations = Operation.paginate(page: params[:page],per_page:5).compras.contado
    render :index
  end

  def compras_credito 
    @operations = Operation.paginate(page: params[:page],per_page:5).compras.credito
    render :index
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def operation_params
    params.require(:operation).permit(:operacion, :pago, 
      :cantidad, :subtotal, :impuestos, :total, 
      :tasa, :balance, :fecha, :comprobante, :user_id, :client_id, 
      :product_id, :cover, :state)
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_footer.html.erb
<footer>
  <ul class="nav nav-pills">
    <li class="boton-footer active", role="presentation", style="a:hover:green"><%= link_to "Retornar", "/operations" %> </li>
    <li><%= link_to " ", operation_path(@operation, :format => 'pdf'), :class => "btn btn-mini btn-success glyphicon glyphicon-save" %></li>
    <% if @operation.may_print? && current_user.is_asistente? %>
      <li class="boton-footer", role="presentation", style="hover:green"><%= link_to  "Editar", edit_operation_path(@operation) %></li>
      <li class="boton-footer", role="presentation", style="hover:green">
      <%= link_to "Emitir", "/operations/#{@operation.id}/print", method: :put, data: { confirm: '¿Estás seguro de emitir esta factura?' } %>
    <%end%>
    <% if @operation.may_pay? && current_user.is_asistente? %>
      <li class="boton-footer", role="presentation", style="hover:green">
      <%= link_to "Pagar", "/operations/#{@operation.id}/pay", method: :put, data: { confirm: '¿Estás seguro de pagar esta factura?' } %>
    <%end%>
    <% if current_user.is_admin? %>
      <li class="boton-footer", role="presentation", style="hover:green"><%= link_to 'Eliminar', @operation, method: :delete, data: { confirm: '¿Estás seguro de eliminar esta factura?' } %></li>
    <%end%>
    </li>
    <% if @operation.may_cancel? && current_user.is_admin?  %>
      <li class="boton-footer", role="presentation", style="hover:green">
      <%= link_to "Anular", "/operations/#{@operation.id}/cancel", method: :put, data: { confirm: '¿Estás seguro de anular esta factura?' } %>
    <%end%>
      </li>
    </li>
  </ul>
</footer>

app/views/operations/_form.html.erb
<% name ||= "Crear" %>
<% if name == "Editar" %>
  <h1><%= name %> Factura  <strong># <%= @operation.id %></strong></h1>
<%else%>
  <h1><%= name %> Factura </h1>  
<%end%>
<% @operation.errors %>
<%= semantic_form_for @operation do |f| %>  
  <%= f.input :operacion, :as => :select, :collection => Operation.operacions.keys.to_a, label: "Tipo de Operación" %>
  <%= f.input :client, label: "Escoja un cliente" %><%= link_to "Crear Nuevo Cliente", new_client_path, :class => 'text-hack' %>
  <br><br>
  <%= f.input :product, label: "Escoja el producto" %>
  <%= link_to "Crear Nuevo Producto", new_product_path, :class => 'text-hack' %>
  <br><br>
  <%= f.input :cantidad %>
  <%= f.input :pago, :as => :select, :collection => Operation.pagos.keys.to_a, label: "Forma de Pago" %>
  <div class="field" style="font-weight: bold;">
    Ingrese el Comprobante (imagen): <%= f.file_field :cover, :class => 'text-hack font-medium' %>
  </div>
  <ul class="nav nav-pills", style="margin:0;padding:0">
    <li class="boton-footer", role="presentation", style="hover:green"> 
      <%= f.submit "Guardar", :class => 'text-hack font-medium', style:"width:200px;height:50px" %>
    </li>
    <li class="boton-footer", role="presentation", style="hover:green">
    <%if name = "Editar"%>
      <%= link_to "Cancelar", @operation, :class => 'text-red font-medium', style:"width:200px;height:50px;background-color:#E4E4E4;border:1px solid grey;border-radius:0;" %>  
    <%else%>
      <%= link_to "Cancelar", "/operations", :class => 'text-red font-medium', style:"width:200px;height:50px;background-color:#E4E4E4;border:1px solid grey;border-radius:0;" %>   
    <%end%>
  </li>
  </ul>
  <br>  
<% end %>

app/views/operations/_navigation.html.erb
<ul class="nav nav-tabs nav-justified">
  <li role="presentation" style="background-color:#e4e4e4;" ><%= link_to "Nueva Factura", new_operation_path %></li>  
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Todas <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Todas", operations_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Borradores", borradores_path %></li>
      <li><%= link_to "Impresas", impresas_path %></li>
      <li><%= link_to "Anuladas", canceladas_path %></li>
      <li><%= link_to "Pagadas", pagadas_path %></li>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Compras <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Todas", compras_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Borrador", compras_borrador_path %></li>
      <li><%= link_to "Impresas", compras_impresas_path %></li>
      <li><%= link_to "Contado", compras_contado_path %></li>
      <li><%= link_to "Crédito", compras_credito_path %></li>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Ventas <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to "Todas", ventas_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Borrador", ventas_borrador_path %></li>
      <li><%= link_to "Impresas", ventas_impresas_path %></li>
      <li><%= link_to "Contado", ventas_contado_path %></li>
      <li><%= link_to "Crédito", ventas_credito_path %></li>
    </ul>
  </li>
  <li role="presentation" ><%= link_to "Por cobrar", ventas_credito_path %></li>
  <li role="presentation" ><%= link_to "Por Pagar", compras_credito_path %></li>
</ul>

app/views/operations/_transactions.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <th>N°</th>
      <th>Operación</th>
      <th>Fecha</th>
      <th>Pago</th>
      <th>Producto</th>
      <th>Monto</th>
      <th>Estado</th>
      <th>Nombre y Apellido</th>
      <th></th>
    </thead>
    <tbody>
      <% @operations.each_with_index do |operation| %>      
      <tr>
        <td><%= operation.id %></td>
        <td class="link-index"><%= link_to operation.operacion, operation %></td>
        <td><%= operation.fecha %></td>
        <td><%= operation.pago %></td>
        <td><%= operation.product.producto %></td>
        <td><%= operation.product.precio %></td>
        <td><%= operation.state %></td>
        <td><%= operation.client.full_name %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/operations/edit.html.erb
<div class="form-center">
	<%= render "form", name: "Editar" %>
</div>

app/views/operations/index.html.erb
<div class="form-center">  
  <strong class="font-large">Facturas:</strong>  
  <%= render "navigation" %>
  <%= render "transactions" %>
  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @operations %>
      <br><br>
    </div>
    <%= will_paginate @operations, :container => false %>
  </div>  
</div>

app/views/operations/new.html.erb
<div class="form-center">
	<%= render "form" %>
</div>

app/views/operations/show.html.erb
<div class="show-center">
  <h1 class="text-center" style="text-transform: uppercase;">  
  <%case @operation.state
  when "Borrador"%>
  <strong>Comprobante de <%= @operation.operacion %> # <%= @operation.id %> </strong></h1>
  <%when "Emitida" || "Pagada" %>
  <strong>Factura de <%= @operation.operacion %> # <%= @operation.id %> </strong></h1>
  <%when ("Emitida" || "Pagada" || "Borrador") && "Anulada" %>
  <strong><%= @operation.operacion %> # <%= @operation.id %> Anulada</strong>
  <%end%>
  </h1>  
  <hr>
  <div class="table-responsive">
    <table class="table table-hover">
      <div class="row">
        <div class="col-md-1"><%= image_tag @operation.client.gravatar_url %></div>
        <div class="col-md-2"><h3><%= @operation.client.tipo %></h3></div>
        <div class="col-md-8"></div>
      </div>
      <thead>
        <th>Nombre y Apellido</th>
        <th>Cédula/RIF</th>
        <th>Email</th>
        <th>Teléfono</th>
        <th>Dirección</th>
      </thead>
      <tbody>
        <tr>
          <td><%= @operation.client.full_name %></td>
          <td><%= @operation.client.identificacion %></td>
          <td><%= @operation.client.email %></td>
          <td><%= @operation.client.telefono %></td>
          <td><%= @operation.client.direccion %></td>
        </tr>
      </tbody>
    </table>
    <table class="table table-hover">
      <h3>Datos de la <%= @operation.operacion %></h3>
      <thead>
        <th>Forma de Pago</th>
        <th>Estado</th>
        <th>Fecha</th>
        <th>Creada por</th>
      </thead>
      <tbody>
        <tr>
          <td><%= @operation.pago %></td>
          <td><%= @operation.state %></td>
          <td><%= @operation.fecha %></td>
          <td><% unless @operation.user.nil? %>
            <%= @operation.user.username %>
          <%end%></td>
        </tr>
      </tbody>
    </table>
    <div class="field">
      <h3>Comprobante de Pago</h3>
      <%= image_tag @operation.cover.url(:medium) %>
    </div>
    <table class="table table-hover">
      <h3>Producto</h3>
      <thead>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Subtotal</th>
        <th>Impuestos</th>
        <th>Total</th>
      </thead>
      <tbody>
        <tr>
          <td><%= @operation.product.producto %></td>
          <td><%= @operation.product.descripcion %></td>
          <td><%= @operation.cantidad %></td>
          <td><%= @operation.product.precio %></td>
          <td><%= @operation.subtotal %></td>
          <td><%= @operation.impuestos %></td>
          <td><%= @operation.total %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <hr>
  <%= render "footer" %>

<br>
<br>
<br>